### ISSUE TITLE
verbosity type comparison error

### ISSUE THREAD

**Issue by dylanhudson** [wummel/patool#104]
hello! 
firstly, thanks so much for all  your work on this awesome tool and the api! 

Wanted to let you know about this error that I received when making the `patoolib.extract_archive()` api call-
>     line 682, in extract_archive
>     if verbosity >= 0:
> TypeError: '>=' not supported between instances of 'str' and 'int'

I'm running Python 3.7 on a 2018 macbook pro with big sur. 

best,

dylan

**Comment by dylanhudson** [comment]
Maybe this is just an issue with the version provided by pip? It's still on 1.12 from 2016. I can't see how this would happen in the current code in this repo, so perhaps this was already fixed.

**Comment by harkabeeparolus** [comment]
> Maybe this is just an issue with the version provided by pip? It's still on 1.12 from 2016. I can't see how this would happen in the current code in this repo, so perhaps this was already fixed.

Unfortunately it seems the original author hasn't been active on this project since 2016, so there have been no new releases, neither here nor on PyPI. 😥

**Comment by wummel** [comment]
Make sure to supply an integer value as verbosity. When in doubt, call
`patoolib.extract_archive(archive, verbosity=int(myverbosity))`
