### ISSUE TITLE
"returned non-zero exit status 7" when using winrar 2.0

### ISSUE THREAD

**Issue by MontraTV** [wummel/patool#108]
I don't know why I'm having this issue but I need to use winrar 2.0 with the project I'm working on. Any other version will not work.

**Comment by harkabeeparolus** [comment]
Winrar 2? That's like 25 years old... 😳 I would not expect any modern tools to support a tool that was discontinued decades ago, so I recommend that you just use your version directly, without patool.

**Comment by wummel** [comment]
I suggest to use a more current version of winrar, or use a custom batch or shell script for your special case.
