### ISSUE TITLE
patool  is multithreaded?

### ISSUE THREAD

**Issue by osevan** [wummel/patool#109]
We need extraction tool,with all cpu cores usage.

Thanks and

Best regards

**Comment by harkabeeparolus** [comment]
Patool is a wrapper script around other extraction tools (and compression, of course).

You need to look for a compression/extraction tool that is itself multithreaded. "patool" has nothing to do with this. For instance:

* Lzip has a great [plzip](https://www.nongnu.org/lzip/plzip.html) tool.
* For *.gz files, look at [pigz](https://zlib.net/pigz/).
* For *.bz2 files, there's [lbzip2](https://github.com/kjn/lbzip2)
* [7-zip](https://www.7-zip.org) -- according to the author, "multithreaded 7z/LZMA2 decompression was implemented in 7-Zip 18.03" (i.e. in 2018).
* For Zstandard, you can [enable multithreading at compile time](https://github.com/facebook/zstd/issues/471#issuecomment-277790593).
* Brotli doesn't yet seem to have official multithreading support, but [zstdmt](https://github.com/mcmilk/zstdmt) can work around that.

> We need extraction tool,with all cpu cores usage.

**Comment by wummel** [comment]
Patool is not multithreaded, but some compression programs are, see the previous answer.
Therefore closing this.
