### ISSUE TITLE
Grab archives' integeritiy test result

### ISSUE THREAD

**Issue by hadi-f90** [wummel/patool#110]
I couldn't find a way to grab archive testing result. nor could I find a method in documentation. 

Is there any way to get a True or False result instead of all those detailed and/or summarized output?

**Comment by harkabeeparolus** [comment]
Patool does return True or False as its shell return code. As is common on Unix, status code 0 (zero) means success, and non-zero means failure.

For example, in bash:

```bash
if patool test archive.zip >/dev/null 2>&1
then
  echo "Success!"
else
  echo "Failure :-("
fi
```

**Comment by hadi-f90** [comment]
What about grabbing the output of the library in a Python program? As far as I saw, the function returns None?

**Comment by wummel** [comment]
See https://github.com/wummel/patool/blob/master/patoolib/cli.py#L63 how to catch a PatoolError and return an error code for archive tests.
