### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by sr-verde** [wummel/patool#114]
Hey guys,

thanks for your work. Would it be possible to release a new version on PyPI soon? Last release is from 2016.

Best!

**Comment by harkabeeparolus** [comment]
Unfortunately the original author has not been active on this project since 2016.

You can install the latest version directly from Github:

```bash
pipx install git+https://github.com/wummel/patool
```

If you don't have pipx (you should!) please see the homepage for installation instructions:
* https://pypa.github.io/pipx/

**Comment by sr-verde** [comment]
No, we don't use pipx and we won't since we use Poetry (but that wasn't the question).

Nevertheless, this Github project is in maintenance. Projects on PyPI can be taken over, the process is also explained in [PEP 541](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer). Sticking to versions would be easier, inexperienced users won't use outdated code from PyPI… There are a lot of good reasons to release a new version (at least here on GitHub).

**Comment by harkabeeparolus** [comment]
I'm sorry if I sounded negative.

I've been trying to modernize the packaging of patool (see my PR #103), ideally moving it over to Poetry (which, by the way, is not an alternative to pipx; they solve completely different problems). Sadly, I haven't seen much activity from the maintainers. I do not believe they have the time and energy to spend on this project. And noone else has stepped up.

I merely wanted to offer a simple workaround for those who want to run the latest version. Obviously that doesn't work if you want the library as a dependency in your project, but it works great for the command line tool.

**Comment by wummel** [comment]
A new version 1.13 of patool has been released on
24.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.

**Comment by sr-verde** [comment]
Yes, I already noticed. Thanks a lot after such a long time without new releases :+1: (I already switched to dtrx, but still...).
