### ISSUE TITLE
patoolib.util.PatoolError: could not find an executable program to extract format compress

### ISSUE THREAD

**Issue by Shimanovroman** [wummel/patool#115]
Hello, i have some problems
I am not good programmer and need this to finish my work for my studies.
I find out that patool can not extract compress files .Z
This format is used by CDDIS and IGS to keep some important files for GNSS Post Processing.
In patoolib/__init__.py in 35 line I couldn't find it in the list .Z format
How I need to fix it? Help me, please
35 line:
ArchiveFormats = (
    '7z', 'ace', 'adf', 'alzip', 'ape', 'ar', 'arc', 'arj',
    'bzip2', 'cab', 'chm', 'compress', 'cpio', 'deb', 'dms',
    'flac', 'gzip', 'iso', 'lrzip', 'lzh', 'lzip', 'lzma', 'lzop',
    'rar', 'rpm', 'rzip', 'shar', 'shn', 'tar', 'vhd', 'xz',
    'zip', 'zoo', 'zpaq')

**Comment by harkabeeparolus** [comment]
The archive format is called **compress**/**uncompress** and [is super ancient](https://en.wikipedia.org/wiki/Compress). The compress file format is indeed [supported by patool](https://github.com/wummel/patool/blob/4928f3fc5083248ec83bbf6b02b5d9089c309100/doc/README.txt#L16). The reason you can't find it in the patool source code is that it is built into the Python standard library:

```python
>>> import mimetypes
>>> mimetypes.guess_type("file.tar.Z")
('application/x-tar', 'compress')
```

You can uncompress a *.Z file with the commands:

* `uncompress file.tar.Z`
* `gzip -d file.tar.Z`
* `gunzip file.tar.Z`
* Or even `zcat file.tar.Z > file.tar`

**Comment by Shimanovroman** [comment]
Thanks!
