### ISSUE TITLE
Я получаю ошибку при распаовке архива, потому что в названии архива присутствует смайлик ❤️

### ISSUE THREAD

**Issue by userqwerty12** [wummel/patool#122]
********** Oops, I did it again. *************

You have found an internal error in patool. Please write a bug report
at https://github.com/wummel/patool/issues/ and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<class 'UnicodeEncodeError'> 'charmap' codec can't encode characters in position 40-41: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\patool", line 213, in main
    res = globals()["run_%s" % args.command](args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\patool", line 33, in run_extract
    patoolib.extract_archive(archive, verbosity=args.verbosity, interactive=args.interactive, outdir=args.outdir)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\patoolib\__init__.py", line 683, in extract_archive
    util.log_info("Extracting %s ..." % archive)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\patoolib\util.py", line 516, in log_info
    print("patool:", msg, file=out)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 40-41: character maps to <undefined>
System info:
patool 1.12
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Local time: 2023-02-19 22:27:21+003
sys.argv ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\patool', '--non-interactive', 'extract', 'C:\\Python\\tokens\\test\\\u2764\ufe0fTEST.rar', '--outdir=C:\\Python\\tokens\\log']
LANG = 'ru_RU.UTF-8'

 ******** patool internal error, over and out ********

**Comment by wummel** [comment]
A new version 1.14.1 of patool has been released on
26.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
