### ISSUE TITLE
[feature request] bash completion

### ISSUE THREAD

**Issue by solsticedhiver** [wummel/patool#127]
There is a file called patool.bash-completion that does not seem to work.

I fixed it by removing the line "have &&", and I end up with a non usefull auto-completion, because it does not give the sub-command extract, ... but file in current directory.

So a working bash completion, is needed.

I could write a basic one, like :
```
complete -W "extract list create test repack recompress diff search formats" patool
```
but it only allows auto-complete for the main subcommand, and then does not show filename... so it is broken too...

**Comment by wummel** [comment]
A new version 1.15.0 of patool has been released on
28.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
