### ISSUE TITLE
Compression level options for bzip3 is invalid

### ISSUE THREAD

**Issue by sorairolake** [wummel/patool#134]
Currently, Options for `bzip3` are as follows:

<https://github.com/wummel/patool/blob/db5edf0e001d069a36cce29ed9a7915fa13d2013/patoolib/programs/bzip3.py#L28>

The usage at bzip3 1.3.2 is as follows:

```
bzip3 - better and stronger spiritual successor to bzip2.
Usage: bzip3 [-e/-z/-d/-t/-c/-h/-V] [-b block_size] [-j jobs] files...
Operations:
  -e/-z, --encode   compress data (default)
  -d, --decode      decompress data
  -r, --recover     attempt at recovering corrupted data
  -t, --test        verify validity of compressed data
  -h, --help        display an usage overview
  -f, --force       force overwriting output if it already exists
  -k, --keep        keep (don't delete) input files (default)
  -v, --verbose     verbose mode (display more information)
  -V, --version     display version information
Extra flags:
  -c, --stdout      force writing to standard output
  -b N, --block=N   set block size in MiB {16}
  -B, --batch       process all files specified as inputs
  -j N, --jobs=N    set the amount of parallel threads

Report bugs to: https://github.com/kspalaiologos/bzip3
```

In other words, `bzip3` does not have options like `-9` or `--fast` like `gzip`.[^1] According to the author, this is intentional.[^2][^3]

Therefore, I think `-9` should be removed.

See also: #129

[^1]: kspalaiologos/bzip3#78
[^2]: <https://github.com/kspalaiologos/bzip3/issues/78#issuecomment-1315313022>
[^3]: <https://github.com/kspalaiologos/bzip3/issues/78#issuecomment-1315769690>

**Comment by wummel** [comment]
A new version 1.14.1 of patool has been released on
26.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
