### ISSUE TITLE
Update CHM parsing

### ISSUE THREAD

**Issue by tlansec** [wummel/patool#135]
This is a duplicate of #78  which was closed as the result of a new release. It looks to me as though archmage is still the default extractor for CHM files.

For CHM files the library developers should consider:

Dropping support for archmage - the lib hasnt been updated in a very long time and isn't python3 compatbile.
Adding support for simple extraction using 7z - today you can extract the subfiles from a CHM file using the 7z binary.

**Comment by wummel** [comment]
The default CHM extraction program in patool is 7z, [see the config](https://github.com/wummel/patool/blob/master/patoolib/__init__.py#L152).
The order in the list is the priority for choosing a program, and 7z is the first list entry.

So if patool does not choose 7z for CHM files on your system, it might be that you do not have 7z installed, or it is not detected properly by patoolib. If 7z is installed but not detected, please provide more info about your system and environment. See for example #35 for a special case where 7z is not detected.

**Comment by wummel** [comment]
Regarding archmage: it depends on the chm library at https://github.com/jedwing/CHMLib.
The library has not been changed in quite some time, but the packages at Linux distributions are still actively maintained, for example the Debian package at https://tracker.debian.org/pkg/chmlib.
As long as there are active package maintainers it does not seem necessary to drop packages and support from patool, so I will mark this as wontfix.

**Comment by tlansec** [comment]
Hey wummel,

I suppose there isn't any harm in keeping support for `archmage`.

In #78 I thought you had blanket closed tickets on the basis that you were closing old tickets which were stale. I hadn't realised that you actually pushed a fix for the issue.

https://github.com/wummel/patool/commit/ef86fcec661ad65ba4e2405d3899e18914b0c301

Closing this ticket.

Thanks,
Tom
