### ISSUE TITLE
Missing some information in Readme.txt

### ISSUE THREAD

**Issue by albert-github** [wummel/patool#136]
In the file `doc/Readme.txt` we see at the bottom the lines:
```
After that typing `patool`, a <SPACE> and then <TAB>
lists available options and commands.
```
Which results in:
![image](https://github.com/wummel/patool/assets/5223533/596bf614-a8c2-4fbe-8aa3-a98b50a1c506)

The `<SPACE>` and `<TAB>` are missing, they should be between single back ticks.

**Comment by wummel** [comment]
Thanks, this is fixed in the git repo.
