### ISSUE TITLE
How to decompress zip volume xxx.zip, xxx.z01 and xxx.z02

### ISSUE THREAD

**Issue by shenmadouyaowen** [wummel/patool#139]
hi,If my compressed file is in the format of xxx.zip, xxx.z01 and xxx.z02, how should I decompress it? Thank you for your answer

**Comment by wummel** [comment]
Assuming those xxx.* files are a split archive: concatenate the parts, then extract the result with patool.

On linux:
`cat xxx.zip xxx.z0* > output.zip`

On windows:
`copy /B xxx.zip xxx.z0* output.zip`

then use `patool extract output.zip`
