### ISSUE TITLE
On OpenBSD: file: unknown option -- uncompress

### ISSUE THREAD

**Issue by rain0r** [wummel/patool#141]
`patool` doesn't work on OpenBSD because its implentation of `file` does not offer the parameter `-z, --uncompress` as in Linux.

```sh
INFO patool: Extracting firefly.gz ...
file: unknown option -- uncompress
usage: file [-bchiLsW] file ...
ERROR patool: ********** Oops, I did it again. *************
```

**Comment by wummel** [comment]
A new version 2.1.0 of patool has been released on
17.01.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
