### ISSUE TITLE
Use official 7-Zip instead of p7zip

### ISSUE THREAD

**Issue by amogus07** [wummel/patool#145]
p7zip uses an old version of 7zip (16.0.2), so patool should use 7zz/7zzs provided by 7-Zip if available instead of 7z/7za/7zG provided by p7zip.

**Comment by wummel** [comment]
A new version 2.1.1 of patool has been released on
26.01.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
