### ISSUE TITLE
Add list_archive result to a list variable support

### ISSUE THREAD

**Issue by timiion** [wummel/patool#148]
OS: Windows 11
Version: 2.2.0
```python
import patoolib
file_list = patoolib.list_archive(archive_path, verbosity=1)
```
list_archive can print the archive list, but return value is None.
Could it support return the file list to a list value.

**Comment by harkabeeparolus** [comment]
This has been asked before, e.g. #44 -- it is very difficult to solve this problem for all archive types, since the tools that Patool use do not return structured data that we could parse.

**Comment by wummel** [comment]
As noted in #44, this will not be implemented.  `ZipFile.infolist()` or `TarFile.getmembers()` can handle this for zip for tar files, if that is what you need.
