### ISSUE TITLE
No module named programs.p7zip

### ISSUE THREAD

**Issue by kallehk** [wummel/patool#15]
I am using windows 7 Enterprise, python 2.7.8, patool 1.7.

When running from cmd:
c:\temp>patool test test.cab                                       
patool: Testing test.cab ...                                       
patool: running "C:\Program Files (x86)\7-Zip\7z.EXE" t -- test.cab
patool: ... tested ok.             
                                  
But when running from within python script:
        patoolib.test_archive('test.cab')
I get following back:
patool: Testing test.cab ...
No module named programs.p7zip

**Comment by wummel** [comment]
the new wheel (.whl) installer file which replaces the .exe installer fixes this
