### ISSUE TITLE
When an archive extension is ended with a number the patool can't determine format on Windows 11

### ISSUE THREAD

**Issue by Risu** [wummel/patool#152]
During porting app from linux to windows I got that issue.
After changing filename from "xxx.7z.001" to "xxx.7z" the patool is recognizing format otherwise I've got "patoolib.util.PatoolError: unknown archive format for file". (The archive is just the one single file, but named like a multi file.)

**Comment by wummel** [comment]
Patool currently uses a programm called [file](https://en.wikipedia.org/wiki/File_(command)) to determine file types. If it is not available (which is usually the case on Windows systems), archives can only be recognized by filename extensions.

Perhaps it would help to add [python-magic](https://github.com/ahupp/python-magic/) or something similar to patool.

**Comment by wummel** [comment]
A new version 3.0.1 of patool has been released on
06.10.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
