### ISSUE TITLE
use piping for search and repack instead of extracting to tmp

### ISSUE THREAD

**Issue by eadmaster** [wummel/patool#154]
this should be a good idea with big archives.

examples:

````
7z e -so test.zip | grep pattern  # patool search (wont pass the filenames this way?)
7z e -so test.zip | 7z a -si test.7z  # patool repack (wont pass the filenames this way?)
````

**Comment by wummel** [comment]
There are several problems with this:

- searching: if any binary file is in the archive, grep detects the whole stream as binary and stops matching
- searching: filenames will not be printed
- repack: not all archive programs support stdout and/or stdin.

I'll add a note to the manual page that search extracts the archive before searching, also with repacking.

**Comment by wummel** [comment]
A new version 2.4.0 of patool has been released on
21.08.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
