### ISSUE TITLE
verbosity not working properly

### ISSUE THREAD

**Issue by timiion** [wummel/patool#157]
OS: Ubuntu 22.04
Version: 2.2.0

```python
import patoolib
patoolib.extract_archive(archive_path, outdir=output_path, verbosity=-1)
```
verbosity was set to -1, -1 or lower means no output. But some info log printed, such as below:
```text
INFO patool: running /usr/bin/tar --force-local --help
INFO patool:     with stderr='-3', input=''
```
Maybe it was caused by
https://github.com/wummel/patool/blob/4c43466eb0b8895eb48c3406fa3b6d93a06dfc85/patoolib/programs/tar.py#L66
Add verbosity to it?

**Comment by wummel** [comment]
A new version 3.0.0 of patool has been released on
25.09.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
