### ISSUE TITLE
Add comment to archive 

### ISSUE THREAD

**Issue by Se7enstars** [wummel/patool#159]
I need to comment archive, but i can't found this function

**Comment by harkabeeparolus** [comment]
It's not in the API or source code for patool. I would recommend you to implement it yourself, or look for other tools.

I do remember this feature from RAR in the 1990's, but it's basically almost never used today. And as far as I can Google, only Zip and Rar formats ever offered support for archive comments. I would guess that most younger IT professionals don't even know this is a thing that existed.

That said, the open source [PeaZip does seem to offer GUI and command line support for it](https://www.reddit.com/r/PeaZip/comments/16dfrw7/comments_in_archive_files/).

**Comment by wummel** [comment]
You can call the archive program with your specific use case directly, ie. by using `zip --entry-comments` . Adding this as a generic use case is not in the scope of patool since most archive formats do not support this.
