### ISSUE TITLE
How to eliminate absolute path in zip archive if absolute paths for files are provided?

### ISSUE THREAD

**Issue by eromoe** [wummel/patool#17]
detail at http://stackoverflow.com/questions/16091904/python-zip-how-to-eliminate-absolute-path-in-zip-archive-if-absolute-paths-for

the post shows `zipfile` has a way to solve this problem, how about patool?

**Comment by wummel** [comment]
Relative paths are written as such in the zipfile.
Example:
mkdir dir1
touch dir1/t.txt
patool create t.zip dir1
[...]
patool list t.zip
dir1/t.txt
