### ISSUE TITLE
Installation and Usage of Patool on windows . import patoollib gives module not found error

### ISSUE THREAD

**Issue by PaarthBatra** [wummel/patool#18]
Hi ,

I need to use patool and my test server is windows . When i try to install patool by : 
pip install patool i get error

Hello i am from site pakages
Downloading/unpacking patool
Downloading patool-1.7.tar.gz (69kB): 69kB downloaded
Running setup.py egg_info for package patool
Hello i am from site pakages

warning: no files found matching 'doc\*.tmpl'
Installing collected packages: patool
Running setup.py install for patool
Hello i am from site pakages
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help

error: option --single-version-externally-managed not recognized
Complete output from command C:\Python2.7.5\python.exe -c "import setuptools
;file='c:\users\abcde\appdata\local\temp\pip_build_abcde\patool\se
tup.py';exec(compile(open(file).read().replace('\r\n', '\n'), file, 'exe
c'))" install --record c:\users\abcde\appdata\local\temp\pip-rbjtsv-record\inst
all-record.txt --single-version-externally-managed:
Hello i am from site pakages

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

or: -c --help [cmd1 cmd2 ...]

or: -c --help-commands

or: -c cmd --help

error: option --single-version-externally-managed not recognized

Cleaning up...
Command C:\Python2.7.5\python.exe -c "import setuptools;file='c:\users\pba
tra\appdata\local\temp\pip_build_abcde\patool\setup.py';exec(compile(open
(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record c:
\users\abcde\appdata\local\temp\pip-rbjtsv-record\install-record.txt --single-v
ersion-externally-managed failed with error code 1 in c:\users\abcde\appdata\lo
cal\temp\pip_build_abcde\patool
Storing complete log in C:\Users\abcde\pip\pip.log

I even tried downloading the windows binary for patool names patool-0.17.exe and patool-1.7.exe however still i am not able to import patool and even when i try to use it from pyunpack i get error

File "D:/unzipping_pyunpack.py", line 13, in 
Archive(rfilename).extractall(rDir)
File "C:\Python2.7.5\lib\site-packages\pyunpack__init__.py", line 83, in extractall
raise ValueError("no backend for archive file: %s (is patool installed?)" % str(self.filename))
ValueError: no backend for archive file: D:\a.rar (is patool installed?)

Can you advice how can this be fixed ?

**Comment by wummel** [comment]
the new wheel (.whl) installer file which replaces the .exe installer fixes this
