### ISSUE TITLE
a plethora of tests failing on Windows

### ISSUE THREAD

**Issue by yarikoptic** [wummel/patool#22]
not that I like to deal with Windows -- I thought to use patool as a panacea for dealing with archives across platforms, thus was running our tests across platforms as well.  But then in attempt to troubleshoot a recent failure on our end decided to run patool's tests on that windows VM -- oh well -- wasn't pleasant. Windows kept popping up with some dialogs about crashed bzip2 etc.  Here you can find the total dump of the 'make test' run on that VM:  http://www.onerussian.com/tmp/patool-make-test-windows.log   cmdline extractors are available as they came with git/git-annex.

**Comment by yarikoptic** [comment]
FWIW  some of them seems to do with the fact that tar  freaks out whenever sees DRIVE: (e.g. c:\\) in the path -- considers it to be a url to remote location.  Feeding to tar or patool the path without c:\  (it is on the same drive after all) seems to resolve the issue - it can access the file

**Comment by wummel** [comment]
Yes, the tar.exe provided by the git package is the reason for the failing tests (and the fact that you have it added to %PATH%). The workaround you suggested works, at least when the current working directory is on the same drive as the archive.
My advise: run test.bat without the tar.exe in the %PATH%, then the tests don't fail.
