### ISSUE TITLE
Could not find an executable program to extract fomar rar

### ISSUE THREAD

**Issue by viniciusbig** [wummel/patool#33]
Hello,
I'm trying to use the patool to open a RAR file.

I've install the patool using pip (patool 1.12)

But using:

```
import patoolib
patoolib.extract_archive("archive.zip", outdir="/tmp")
```

I get the error: 
`PatoolError: coud not find an executable program to extract format rar; candidates are (rar,unrar,7z)`

I'm using Python 2.7 and a Mac OS El Capitan

What i'm missing? I couldn't find any tutorials or help for that.
Thanks for any help

**Comment by wummel** [comment]
Patool needs a command line archive tool to extract RAR files.
On OSX you should be able to install that with brew, eg. "brew install unrar".
