### ISSUE TITLE
TypeError: extract_archive() got an unexpected keyword argument 'interactive'

### ISSUE THREAD

**Issue by TonnyCZ** [wummel/patool#34]
<type 'exceptions.TypeError'> extract_archive() got an unexpected keyword argument 'interactive'
Traceback (most recent call last):
  File "/opt/django/gc2/env/bin/patool", line 213, in main
    res = globals()["run_%s" % args.command](args)
  File "/opt/django/gc2/env/bin/patool", line 33, in run_extract
    patoolib.extract_archive(archive, verbosity=args.verbosity, interactive=args.interactive, outdir=args.outdir)
TypeError: extract_archive() got an unexpected keyword argument 'interactive'
System info:
Patool 1.4
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Local time: 2016-01-22 12:42:31+002
sys.argv ['/opt/django/gc2/env/bin/patool', 'extract', '/opt/django/gc2/gc2/media/files/storage1/logged-users/2/2016-01-22_12-42-25/in/test.tar.gz', '--outdir=/opt/django/gc2/gc2/media/files/storage1/logged-users/2/2016-01-22_12-42-25/in']
LANGUAGE = 'en_US'
LC_ALL = 'en_US.UTF-8'
LANG = 'en_US.UTF-8'

 ******** Patool internal error, over and out ********

**Comment by wummel** [comment]
It seems you are using a newer command line script with an older version 1.4 of the patoolib library. Please check that you are using the latest version 1.12.
