### ISSUE TITLE
patool fails to find 7-Zip on windows 64bit

### ISSUE THREAD

**Issue by jacobEAdamson** [wummel/patool#35]
When running 32 bit python on Windows AMD64, patool does not properly add the 7-zip directory to the path when looking for programs to extract with.

Code should be updated to use the proper key opening when the user is on AMD64 windows. Fixed function attached.
[updated.zip](https://github.com/wummel/patool/files/149760/updated.zip)

**Comment by wummel** [comment]
A new version 1.15.0 of patool has been released on
28.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
