### ISSUE TITLE
patool should avoid conflating its diagnostic logging with target output of the commands

### ISSUE THREAD

**Issue by yarikoptic** [wummel/patool#37]
ATM all of the output is simply provided to stdout, and I don't see any '--quiet' option which would prevent any internal output from patool (atm on 1.10 from debian), so 
1. situation could be as confusing as

```
$> patool list package_maker.tar.gz 2>/dev/null
patool: Listing package_maker.tar.gz ...
patool: running /bin/tar --list -z --file package_maker.tar.gz
patool: Listing
patool: Listing package_maker.tar.gz ...
```

(noone forbids files like `patool: Listing` in the archive ;) )
1. at the level of python module, either monkey patching logging facilities or just running patool commands while swallowing all stdout to avoid printouts to the stdout when non desired (see e.g. our ugly attempts to mitigate here: https://github.com/datalad/datalad/blob/master/datalad/support/archives.py#L34)

IMHO it would be sweet if patool just used standard python's logging module for logging and possibly even directed its diagnostic output to stderr (as e.g. git does), while such commands as `list` have used stdout solely for their output.

Also would be neat to have e.g. `--quiet` option of operation which wouldn't spit out any logging unless there is an error

Cheers and thanks!

**Comment by sanand0** [comment]
+1 for the use of the Python `logging` module. Replacing the `print` functions in `patool.util.log_*` with the appropriate `logging.*` methods would work, I believe.

May I submit a merge request?

**Comment by hakandilek** [comment]
> May I submit a merge request?

Hey @sanand0, did you submit those commits as MR? I don't see those changes on `master` branch.

**Comment by sanand0** [comment]
@hakandilek -- no, I didn't work on this

**Comment by wummel** [comment]
A new version 2.0.0 of patool has been released on
14.11.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
