### ISSUE TITLE
don't store full absolute paths in a tar archive

### ISSUE THREAD

**Issue by vitlav** [wummel/patool#38]
When use patool for tar archive creating, like
$ patool create some.tar /path/to/dir
created tarball will contains path/to/dir path.
With other type of archives (zip, 7z, etc) all is ok: only last component will in a archive.

**Comment by alwaysharsha** [comment]
Adding support to ignore absolute paths in tar archive would be very useful.

**Comment by wummel** [comment]
The tar program stores path names the way they are given on the command line. If you like to store relative path names, change into the parent directory first:
`cd /path/to; patool create some.tar ./dir`
