### ISSUE TITLE
Support for the package unar

### ISSUE THREAD

**Issue by admirabilis** [wummel/patool#39]
File Roller has switched to [unar](https://unarchiver.c3.cx/commandline) instead of unrar-nonfree to extract RAR files, since unar has very good support for the different RAR formats, besides being released under a free license. patool fails to extract RAR files on my system, since I don't have unrar installed on my system (of course I can install unrar, but not depending on non-free software is the issue at hand).

**Comment by wummel** [comment]
A new version 1.15.0 of patool has been released on
28.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
