### ISSUE TITLE
PyPI wheel format has incorrect patool shebang line

### ISSUE THREAD

**Issue by msmith491** [wummel/patool#40]
The source code for the `patool` script correctly has a shebang line of `#!/usr/bin/env python`

However, if you `pip install patool` in a clean environment and ensure you're using wheels rather than building from the github source, the shebang line is changed.  Instead it now has `#!/usr/bin/python` which means if you're running in a virtualenv, the script tries to reference the system python which may not have `patool` installed.

You can verify the contents of the wheel on PyPI by doing the following:
1.  Go to https://pypi.python.org/pypi/patool/
2.  Download the listed wheel on that page.  Available from this link: https://pypi.python.org/packages/43/94/52243ddff508780dd2d8110964320ab4851134a55ab102285b46e740f76a/patool-1.12-py2.py3-none-any.whl#md5=d8ce0b8cff19d7afeb38db4ec9cddb3c
3. Unzip the wheel into a folder: `unzip patool-1.12-py2.py3-none-any.whl`
4. Look at the `patool` script under `patool-1.12.data/scripts`
5. You will see that it has the `#!/usr/bin/python` shebang instead of `#!/usr/bin/env python`.

**Comment by wummel** [comment]
patool >= 1.13 uses the [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) mechanism of setuptools, so installing the newest version fixes this.
