### ISSUE TITLE
Allow passwords on non-interactive

### ISSUE THREAD

**Issue by cledoux** [wummel/patool#43]
I need an ability to provide passwords on non-interactive runs of patool.

I don't actually need this on the cli, but only through programmatic support. Essentially, I need the functions `patool.extract_archive` and `patool.create_archive` to take an optional password parameter. If the password parameter is not None, use the provided password for extraction or creation.

I'm more than willing to implement this myself. 

Is this a feature you would take a pull request for? If so, do you want to expose this feature via a cli option and  how do you want to handle archive formats that don't support a password? My plan was to log a warning if a password is passed to an unsupported format. If the capability is exposed via cli, I was going to explicitly state in the option the list of formats that support a password.

**Comment by wummel** [comment]
patool itself and the api functions now take an optional password
