### ISSUE TITLE
patool not responding

### ISSUE THREAD

**Issue by attibalazs** [wummel/patool#45]
```
if extension.lower() in ['.zip', '.rar']:
    patoolib.extract_archive(archive=doc['url'], outdir=os.path.join(os.getcwd(), temp_folder))
```
```
patool: Extracting C:\Temp\docmover_temp\temp\Afternoon Reports.rar ...
patool: running "C:\Program Files\7-Zip\7z.EXE" x -oC:\Temp\docmover_temp\temp -- "C:\Temp\docmover_temp\temp\Afternoon Reports.rar"
```

I noticed that patool is unresponsive when i run it from python, since the files already exist at the output location.

if i take that command and run it in a command prompt it prompts me for an action : "would you like to overwrite the existing file?"

thanks,
Atti

**Comment by fiendish** [comment]
set interactive=False in your extract_archive call

**Comment by wummel** [comment]
patool >= 1.13 disables password prompting when using interactive=False, closing.
