### ISSUE TITLE
uncompressed nested compress file

### ISSUE THREAD

**Issue by neo1parekh** [wummel/patool#47]
This is my compressed file structure.

mainzip is the primary file, mainfileA1.zip & mainfileA2.zip is the 2 file inside the mainzip file

I want to extract main zip file with all the inner zip file too.

**mainzip.zip**

- mainfileA1.zip

- mainfileA2.zip

Kindly suggest the solution.

**Comment by wummel** [comment]
This  is not supported by patool. You can write a custom shell or batch script for your needs.
