### ISSUE TITLE
large zip -- use jar to extract? unzip uses -v (list files) while extracting?

### ISSUE THREAD

**Issue by yarikoptic** [wummel/patool#49]
from time to time we encounter some large .zip files so I guess some version of ZIP64 support is enabled/used. e.g. now got 16GB zip

patool tries to use 7z on those but that one blows right away without even trying to extract anything.  I have tried to trick it with
```python
patoolib.ArchivePrograms['zip'].pop(None)
```
to cause it to use `unzip`.  But that one also blows right away on `unzip -v -- file -d outdir` command, and `-v` is apparently a flag not to be verbose, but to cause listing of the files in the archive.  So I wondered if that is correct behavior.

Well -- even without '-v' unzip also doesn't work fully correctly -- just extracts some first 4GB of data and then exits with -2.

This was on a Debian jessie box, tried also with patool straight from git.

So overall question is -- have you encountered large zip files patool (with the tools employed) could not extract? ;)

**Comment by yarikoptic** [comment]
ha!  I have tried `jar xf` and it completed without error!  jar was from `/usr/lib/jvm/java-7-openjdk-amd64/bin/jar` from 7u101-2.6.6-1~deb8u1 of openjdk-7-jdk:amd64

I guess if patool supports jar for that purpose would be cool... also if it could sweep through available extractors (if it doesn't do yet) then it all might work splendidly

**Comment by yarikoptic** [comment]
@wummel any ideas on how to approach supporting jar here (and fixing unzip invocation)?

**Comment by wummel** [comment]
A new version 2.0.0 of patool has been released on
14.11.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
