### ISSUE TITLE
Create Archive Example

### ISSUE THREAD

**Issue by achapkowski** [wummel/patool#50]
Hello,

I have a question about create_archive and filenames.

```patoolib.create_archive("/path/to/myfiles.zip", ("file1.txt", "dir/"))```

How do you compress a folder and all the sub-folders?
If you want a file to go into a specific location in the compress folder like:

```
'root_file.txt'
'/subfolder/sub_folder.txt'
```

How do you pass that into the create_archive?

Thank you

**Comment by wummel** [comment]
Just supply the directory names in the filenames list as you already specified:
`patoolib.create_archive("my.zip", ("file1.txt", "dir/"))`
