### ISSUE TITLE
Call for contributions

### ISSUE THREAD

**Issue by yarikoptic** [wummel/patool#66]
Echoing #58 I would like to invite patool users to contribute to patool development.  There is a number of possible ways you could contribute:

# Bug fixing

There is a number of oustanding issues from various eras of patool/Python.  So your contributions to have them addressed are more than welcome!

- now that coverage reporting is in place, make sure that your contribution is accompanied with a test and improves coverage

# Testing

As https://codecov.io/gh/wummel/patool shows many aspects of patool operation are not tested at all.
So it might be relatively easy and most impactful in the long run way to contribute - provide testing for code paths which are not yet tested at all.

**Comment by jayvdb** [comment]
I was trying to package this as an rpm, and noticed that some of the tests in the last release fail because of missing data.

I see some new data files added since the last release, but it looks like they havent been included in `MANIFEST.in`.
Do you plan to include test data in the sdist?  If so, I can help do that, but I occasionally encounter authors who object to tests / test data in the sdist.  I see you are building wheels, so I dont see any reason why the sdist cant be larger, including test data.

**Comment by eclipseo** [comment]
Fedora maintainer here.
I have a couple of patch onto 1.12 that I have not upstreamed due to the lack of maintainer:
https://src.fedoraproject.org/rpms/patool/tree/master
They fix the tests for me.

**Comment by jayvdb** [comment]
Awesome. Thanks.  OpenSUSE here; I'll borrow those happily, but I notice that .spec is using GitHub archive rather than sdist.  I'm hoping the next sdist will be better.

**Comment by jayvdb** [comment]
@eclipseo , my spec is at https://build.opensuse.org/package/show/home:jayvdb:rpm/python-patool .  It has a few extra patches , and a different subset of programs due to programs missing in openSUSE .  I'll submit PRs here tomorrow for my fixes.

**Comment by yarikoptic** [comment]
Please submit PRs for anything worthwhile upstream - I will try to do my best to not miss them ;-)

**Comment by abitrolly** [comment]
Before submitting anything it would be nice to see a newer version released. The latest one was cut 5 years ago and in Fedora it gives this autocompletion error in bash on filenames.
```
$ patool list duff bash: completion: function `_patool' not found
```

**Comment by wummel** [comment]
The code dependencies for development as well as the build process are modernized now. See [doc/development.md](https://github.com/wummel/patool/blob/master/doc/development.md) for more info how to start developing with this code.
