### ISSUE TITLE
gzip extraction (if via plain gzip) does not recover original filename

### ISSUE THREAD

**Issue by yarikoptic** [wummel/patool#67]
When a file (here `123`) is gzipped, and then renamed, original filename is still known within the archive:
```shell
$> file renamed.gz
renamed.gz: gzip compressed data, was "123", last modified: Fri Feb 22 20:02:38 2019, from Unix, original size 0
```
and extracts it as `123` if p7zip is installed
```shell
$> python -c 'import patoolib as p; p._extract_archive("renamed.gz", outdir=".", verbosity=100)'
patool: running /usr/bin/7z e -o. -- renamed.gz

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (40651),ASM,AES-NI)

Scanning the drive for archives:
1 file, 24 bytes (1 KiB)

Extracting archive: renamed.gz
--
Path = renamed.gz
Type = gzip
Headers Size = 14

Everything is Ok

Size:       0
Compressed: 24
patool: ... renamed.gz extracted to `.'.
(dev) 1 25021.....................................:Fri 22 Feb 2019 10:58:51 PM EST:.
hopa:/tmp
$> ls -l 123
-rw------- 1 yoh yoh 0 Feb 22 15:02 123
```
but if no p7zip, unfortunately patool invokes `gzip` without consideration for original filename, and using `>`
```shell
$> python -c 'import patoolib as p; p._extract_archive("renamed.gz", outdir=".", verbosity=100)'
patool: running '/bin/gzip' -v -c -d -- 'renamed.gz' > './renamed'
patool:     with shell='True'
renamed.gz:	  0.0%
```
thus loosing original name and making behavior inconsistent depending on which extractor is used

**Comment by wummel** [comment]
The reason patool uses the `-c` option with stdout redirection is that otherwise gzip writes its output in the same directory of the archive, not into the given output directory.
It might be necessary to parse the output of `gzip -l` to obtain the original filename, at least I have no other idea on how to achieve this.

**Comment by harkabeeparolus** [comment]
> The reason patool uses the `-c` option with stdout redirection is that otherwise gzip writes its output in the same directory of the archive, not into the given output directory. It might be necessary to parse the output of `gzip -l` to obtain the original filename, at least I have no other idea on how to achieve this.

You could use a similar strategy as `jc` does for parsing text tables such as the one generated by `gzip -l`. See for instance [simple_table_parse()](https://github.com/kellyjonbrazil/jc/blob/249d93f15c877855c08454aa5c34905bc6c27f35/jc/parsers/universal.py#L5) which is used e.g. to convert `zipinfo` output to JSON, e.g. `jc -p zipinfo myfile.zip`. The good thing about this parser is that it will accept whitespace in the final column which contains the file name.

**Comment by wummel** [comment]
A new version 2.0.0 of patool has been released on
14.11.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
