### ISSUE TITLE
ImportError: No module named patoolib

### ISSUE THREAD

**Issue by niksfirefly** [wummel/patool#68]
Ubuntu, install via pip3 in pyenv - python 3.7
when run
ImportError: No module named patoolib
regards

**Comment by zaee-k** [comment]
Can You paste full pip command You use to download this?

**Comment by bubalazi** [comment]
This bug can be reproduced by

```shel
virtualenv .venv
source .venv/bin/activate
pip install patool
patool
Traceback (most recent call last):
  File "/home/lpetrov/projects/raptor/components/puv2/.venv/bin/patool", line 24, in <module>
    import patoolib
ImportError: No module named patoolib
```

Changing the shebang in file `.venv/bin/patool` to:
```shell
#!/usr/bin/env python
```
solves the problem.

**Comment by RotemEmergi** [comment]
there is any auto way to enforce to use python path ?

**Comment by highandmighty** [comment]
The same problem on Mac OS, where Python 3 users usually use `python3` (and `pip3` to install modules), as `python` and `pip` are reserved for default OS Python 2.

In this scenario module `patoolib` can be imported correctly in Python 3 while command-line tool doesn't work.

Changing shebang in `/Library/Frameworks/Python.framework/Versions/3.7/bin/patool` to `#!/usr/bin/env python3` finally makes it work.

**Comment by mrakitin** [comment]
Just encountered the same problem when tried to use the library from within a conda environment, where the package was installed from the wheel package (`pip install patool`). I also had to change the hard-coded `#!/usr/bin/python` (`#!/usr/bin/env python` seems to work).

`#!/usr/bin/python` somehow magically appears in the `patool-1.12.data/scripts/patool` file in the wheel package on PyPI, probably based on the Python executable path on the machine where it was packaged. Only the shebang line is different comparing to the https://github.com/wummel/patool/blob/master/patool file in this repo. It would be much more robust if the installation was using the [entrypoints](https://packaging.python.org/specifications/entry-points/), where the script is generated during the installation phase, not the building phase.

@wummel, are there any considerations about updating `setup.py` to use entrypoints?

**Comment by federicodifresco** [comment]
Hi!

Installing patool in the terminal with the following line worked for me:

pip install patool

I am using:

Mac OS High Sierra 10.13.6
Python3.7
Spyder

Normaly I'll use pip3 – in this case it didn't work and when I tried with pip it did :)

**Comment by yarikoptic** [comment]
> It would be much more robust if the installation was using the [entrypoints](https://packaging.python.org/specifications/entry-points/), where the script is generated during the installation phase, not the building phase.

I also think that switching to use of entrypoints is the way to go.  If someone proposes a PR I promise to review/accept when ready.

**Comment by teresaejunior** [comment]
Quick install of patool with Python3:
```
sudo pip3 install patool
sudo sed -i '1 s/python$/python3/' /usr/bin/patool
```

**Comment by harkabeeparolus** [comment]
This is fixed now with the new release of patool which uses entry points.
I believe this issue should be closed.

**Comment by wummel** [comment]
The usage of entry points in https://github.com/wummel/patool/blob/master/setup.py fixes this.

**Comment by yundy1** [comment]
You can use：
pip install patool
(ubuntu 22.4+virtualenv )
