### ISSUE TITLE
Support python module rarfile

### ISSUE THREAD

**Issue by jayvdb** [wummel/patool#69]
https://rarfile.readthedocs.org/ would be a good substitute for rar.

Also python PYPY package https://github.com/openSUSE/unrar_wrapper could be a proxy for supporting [unar and lsar](https://theunarchiver.com/command-line)

**Comment by jayvdb** [comment]
I see native unar support is https://github.com/wummel/patool/issues/39

**Comment by wummel** [comment]
unar is supported now, closing this. Thanks for the report.
