### ISSUE TITLE
*.i586.rpm: cpio(1) is required for rpm2cpio extraction; please install it 

### ISSUE THREAD

**Issue by cyrlhq** [wummel/patool#71]
Hi, I tried to use pyunpack and patool to unpack files from rpm with "Archive('*.i586.rpm').extractall('extract_rpm')" on Python Console. 
However, the patool error reflects a "cpio(1) is required for rpm2cpio extraction; please install it". I am wondering what package it implies to install as I tried "pip install rpm2cpio" but it seems there is no Python Libraries named 'rpm2cpio'. BTW, the Python Version I am using is 3.6.

**Comment by zaee-k** [comment]
I think You need to install 'cpio' program for your system. Depending on used OS, for debian You can use `apt-get install cpio`

**Comment by cyrlhq** [comment]
> I think You need to install 'cpio' program for your system. Depending on used OS, for debian You can use `apt-get install cpio
I tried but this does not work. I am using Python on Windows environment, the 'pip install cpio' will result for a 'No matching distribution found for cpio' in CMD.

**Comment by zaee-k** [comment]
But the 'cpio' isnt pip package - it is standalone program. Just like 'ls', 'cat' in linux system, patool uses 'cpio' to unpack the files You want. You need to check if 'cpio' is available for windows.

**Comment by cyrlhq** [comment]
> But the 'cpio' isnt pip package - it is standalone program. Just like 'ls', 'cat' in linux system, patool uses 'cpio' to unpack the files You want. You need to check if 'cpio' is available for windows.

Thank you for the the instruction. Which fold should I download cpio into? Is it under the same folder as the rpm2cpio program?

**Comment by wummel** [comment]
For windows, you can install [7z](https://7-zip.org/), which support extracting RPM archives.
