### ISSUE TITLE
Extention is added to archive name when 7z is used

### ISSUE THREAD

**Issue by FunkyLoiso** [wummel/patool#72]
`7z` has command line option [-sa](https://sevenzip.osdn.jp/chm/cmdline/switches/sa.htm):

Switch | Description
-- | --
-saa | Always add archive type extension.
-sae | Use exact name specified in command.
-sas | Add extension only if specified name has no extension.                             It's default option.

`patool` does not set any of this flags, so by default archive name is modified when if does not contain extension. As a result the created archive may be inaccessible via path provided to `create_archive`.

I suggest adding `-sae` option when using `7z`.

**Comment by wummel** [comment]
A new version 2.0.0 of patool has been released on
14.11.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
