### ISSUE TITLE
Add UDF / Bluray support

### ISSUE THREAD

**Issue by benvaljean** [wummel/patool#80]
It would be great if patool support UDF / Blurays. Currently is tries to use 7-Zip but it only supports ISO 9660 (DVD/CD) .

**Comment by harkabeeparolus** [comment]
Apparently 7-Zip supports UDF now according to the author Igor Pavlov, at least partly. Some sector sizes might not work yet.
* https://sourceforge.net/p/sevenzip/discussion/45797/thread/f91b702fa3/
