### ISSUE TITLE
verbosity not work when use pythonw

### ISSUE THREAD

**Issue by richardkiwilee** [wummel/patool#85]
7z test_archive verbosity doesn't work when using pythonw mode.
In util.py -> def run (cmd, verbosity=0, **kwargs):
you will need use:
CREATE_NO_WINDOW = 0x08000000
subprocess.call(TARGET_FILE, creationflags=CREATE_NO_WINDOW))

**Comment by wummel** [comment]
A new version 1.14.1 of patool has been released on
26.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
