### ISSUE TITLE
Problem with tar.EXE unpackling tar.xz on Windows 10

### ISSUE THREAD

**Issue by rpr13** [wummel/patool#86]
Hi.

There is problem on unpack `tar.xz`.
log:
```
PS C:\Users\rpr> C:\WINDOWS\system32\tar.EXE --extract --use-compress-program xz --file C:\Users\rpr\AppData\Local\portmod\portmod\Cache\downloads\adamantiumarmor-umopp-3.0.2.tar.xz --directory C:\Users\rpr\AppData\Local\Temp\portmod\items-armor\adamantium-armor-1.0\work\adamantiumarmor-umopp-3.0.2
tar.EXE: Error opening archive: Can't initialize filter; unable to run program "xz"
```
tar.exe version:
```
PS C:\Windows\System32> .\tar.exe --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
```
`tar.gz` works ok.

Writing about this, because `patool` is using this.

Maybe `patool` should use some other unpacker if problem occured?
There is `7zip` on system, and it works ok with `tar.xz`.

**Comment by rpr13** [comment]
https://github.com/wummel/patool/blob/30716c1ea02743b2c31e65ea83faae04e53252da/patoolib/programs/tar.py#L53

This might be the problem.

Windows `tar.exe` is `bsdtar`.

**Comment by rpr13** [comment]
I kind of managed to work around it.

Downloaded new official `bsdtar.exe`, changed name to `tar.exe` and added it to `PATH`. ([libarchive](https://www.libarchive.org/))

Propably `patool` also need to check if it is really `tar.exe` or `bsdtar.exe` 😄

**Comment by wummel** [comment]
Right now the detection of different tar implementation mostly uses the executable name. Perhaps using "tar --version" is more robust.

**Comment by harkabeeparolus** [comment]
Seems viable. On latest macOS:

```
❯ tar --version
bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.12 liblzma/5.0.5 bz2lib/1.0.8
```

And on a pretty recent Devuan Linux:

```
❯ tar --version
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

Both bsdtar and GNU tar seem to have the `--use-compress-program=PROG` flag, so that's good. (They also both have a flag for automatically compression format based on the file name:   `-a, --auto-compress        use archive suffix to determine the compression program`.) However, only bsdtar seems to do automatic format detection while **reading** from an archive.

On older or more obscure Unixen, all bets are off. ☹️

**Comment by wummel** [comment]
A new version 3.0.0 of patool has been released on
25.09.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
