### ISSUE TITLE
Could not find an executable program to extract format rar

### ISSUE THREAD

**Issue by Fuzl** [wummel/patool#90]
Hello and a great BRAVO for this nice lib I discovered a few days ago !

Unfortunately I have a little bug with some RAR files.
On Debian I have setup p7zip-full and patool 1.12 and want to uncompress a `.rar` archive with patool.
Unfortunately I have the error message in Subject.
I can execute from bash `7z e myfile.rar` and it will uncompress the archive.
Any idea what can cause this ?
Thanks,
Fuzl.

**Comment by Fuzl** [comment]
I found something strange, 7z will send me "Unsupported Method" errors with the `x` argument.
How come it works with `e` and not with `x` ? 
```shell
root@a9a9f7d9eb97:/workspace# 7z x 39.rar

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1374292969 bytes (1311 MiB)

Extracting archive: 39.rar
--
Path = 39.rar
Type = Rar
Physical Size = 1374292969
Solid = -
Blocks = 3802
Multivolume = -
Volumes = 1

ERROR: Unsupported Method : XXXX.jpg
ERROR: Unsupported Method : XXXX.jpg
...
```

**Comment by Fuzl** [comment]
Ok, so it is explicitely stated on Debian package website that :
"p7zip-rar provides a module for p7zip-full to make 7z able to extract RAR files."

So I allowed non-free Debian repositories with : 
```
apt install -y software-properties-common
add-apt-repository non-free
apt-get update
```

Then added p7zip-rar : 
`apt-get install -y p7zip-rar`

And then... well, it worked ;o)
Still strange that 7z *does* extract files with the `e` argument without p7zip-rar. Might ease things if patool could use that.

**Comment by Fuzl** [comment]
It seems I was a little too quick closing that issue.
Patool does not see the p7zip-full and p7zip-rar packages as it checks for 'p7zip/Codecs/Rar29.so' which in recent versions of p7zip seems to have been renamed to 'p7zip/Codecs/Rar.so'. This is in `util/p7zip_supports_rar()`.

With 4 open PR at the time of writing is there any use opening a fifth one ?
@yarikoptic  any clue ?

**Comment by RootEncrypter** [comment]
i have winrar installed by default but when i use patool to create an archive i still an error:
could not find an executable program to create format rar; candidates are (rar),
i even installed 7zip but the problem still seems to be there

im using python and my code is:
patoolib.create_archive("test.rar",("test.txt",))

**Comment by Fuzl** [comment]
I would recomend not using Patool, see my answer here : https://stackoverflow.com/a/63915155/7541501

**Comment by wummel** [comment]
The 7z rar detection has been fixed in recent versions, closing.
