### ISSUE TITLE
No module named 'patool' on Windows 

### ISSUE THREAD

**Issue by tohe3007** [wummel/patool#92]
When installing via pip or via the whl file the same error occurs. 
I was looking for days until I finally got to the root of the issue.

Basically, the patool is correctly installed in the /scripts folder, however the file "patool" that got installed into the script folder misses the file extension. I figured that to be ".py" not ".exe".

By renaming that file to "patool.py" the issue is resolved.

Can you please fix this issue in the code base for others as well?

Environment: Windows 10, Python 3.7 (original no Anaconda)

**Comment by wummel** [comment]
The current version (1.14) installs a patool.exe script which should work without issues.
