### ISSUE TITLE
Doesn't extract tar from tar.xz 

### ISSUE THREAD

**Issue by Alarmfifa** [wummel/patool#94]
I found a strange behavior with *.tar.xz archives. If I try to extract it (for example using bash utility patool) it will only uncompress. So instead of a folder with files, I receive only one *.tar file.

Tried to investigate why it worked this way, I found the following things:

This trick https://github.com/wummel/patool/blob/6b1f82e2d23e2b2646ebe8403aa69ef6fd1df139/patoolib/util.py#L294 doesn't work with tar.xz. For tar.gz - it's ok, no problem.
```
file --brief --mime --uncompress archive.tar.xz
Bad system call
file --brief --mime --uncompress archive.tar.gz      
application/x-tar; charset=binary compressed-encoding=application/gzip; charset=binary
```
But it is not an exception, that you catch below. That's why this method return information only about `application/x-xz` encoded file.

There is a good python library, that you use too - mimetypes. And it returns correct info:
```
>>> mimedb.guess_type('archive.tar.xz')
('application/x-tar', 'xz')
```
I added workaround, but met another problem. tar.xz extracted without subfolder. All files lays directly, that's why patool create a folder by itself, but give a wrong name for it - `archive.tar` (not file, it is a folder name), instead of `archive`.
Here you cut only one extension (.xz) https://github.com/wummel/patool/blob/6b1f82e2d23e2b2646ebe8403aa69ef6fd1df139/patoolib/util.py#L497

My dirty hack and workaround looks like this and with this patch patool works correctly with tar.xz.
```(patch)
299a300,301
>         if (outparts[0] == ""):
>             mime, encoding = guess_mime_mimedb(filename)
497c499,502
<     return os.path.splitext(os.path.basename(filename))[0]
---
>     basename = os.path.splitext(os.path.basename(filename))[0]
>     if (basename[-3:] == 'tar'):
>         basename = os.path.splitext(basename)[0]
>     return basename
```
Maybe it will help =)

**Comment by wummel** [comment]
archive fie name with .tar.xz is fixed in the latest patool version, see https://github.com/wummel/patool/blob/8358491e7f9cabcbf3728cc490525ef925fd4cb1/patoolib/fileutil.py#L83
